//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetWork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long IdMessage { get; set; }
        public long IdUser { get; set; }
        public string Content { get; set; }
    
        public virtual Users User { get; set; }
    }
}
